upstream_package_name: rhc-worker-playbook
downstream_package_name: rhc-worker-playbook
specfile_path: rhc-worker-playbook.spec

srpm_build_deps:
  - make
  - python3dist(cython)
  - python3dist(pip)
  - python3dist(wheel)
  - rpm-build

actions:
  get-current-version:
    - awk '/^Version:/ {print $2;}' rhc-worker-playbook.spec
  create-archive:
    - make tarball
    - bash -c 'echo dist/rhc-worker-playbook-*.tar.*'
  fix-spec-file:
    - bash -c 'echo "No action needed"'

jobs:
  - job: copr_build
    trigger: pull_request
    additional_repos:
      - "copr://@yggdrasil/latest"
    targets:
      - centos-stream-9
      - rhel-8
      - rhel-9

  - job: copr_build
    trigger: commit
    branch: main
    owner: "@yggdrasil"
    project: latest
    targets:
      - centos-stream-9
      - rhel-8
      - rhel-9
