name: dist

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:latest
    steps:
      - run: dnf install --setopt install_weak_deps=False --assumeyes golang git-core meson 'python3dist(pip)' 'pkgconfig(yggdrasil)' 'pkgconfig(dbus-1)' 'pkgconfig(systemd)' jq ansible-core
      - uses: actions/checkout@v4
      # See https://github.com/mesonbuild/meson/pull/13637
      - run: git config --global safe.directory "*"
      - run: meson setup -Dvendor=True _build
      - run: meson dist -C _build
      - uses: softprops/action-gh-release@v2
        with:
          files: _build/meson-dist/rhc-worker-playbook-*.tar.xz*
